version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPO_URI="481071950406.dkr.ecr.ap-south-2.amazonaws.com"
      - aws ecr get-login-password --region ap-south-2 | docker login --username AWS --password-stdin $REPO_URI

  build:
    commands:
      - echo Build started on `date`
      - docker build -t go-ecs-demo .
      - docker tag go-ecs-demo:latest $REPO_URI:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPO_URI:latest
      - printf '[{"name":"go-ecs-demo","imageUri":"%s"}]' $REPO_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

